name: run test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest httpx ruff
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "server/requirements.txt"
      - name: Test with pytest
        run: |
          cd server || coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: |
          cd server || coverage report -m
      - name: Ruff check
        run: ruff check  --fix
      - name: Test with pytest
        run: |
          cd server || coverage run -m pytest test -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
